"""Add position, skills, and experience_level to users

Revision ID: 9621d195d4e2
Revises: c1a1bd36567d
Create Date: 2024-11-14 12:50:45.840939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9621d195d4e2'
down_revision: Union[str, None] = 'c1a1bd36567d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('position', sa.String(), nullable=True))
    op.add_column('users', sa.Column('skills', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('experience_level', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'experience_level')
    op.drop_column('users', 'skills')
    op.drop_column('users', 'position')
    # ### end Alembic commands ###
